name: Sync submodule
# sync submodule each day

on:
  schedule:
  - cron: "0 */4 * * *"

jobs:
  submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: submodule update
        run: git submodule update --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
