name: Sync submodule
# sync submodule each day

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Github configuration
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
      - name: Github update submodule
        run: git submodule update --remote --recursive
      - name: Adding to github
        run: |
          git add .
          git commit -m "Update submodules" && git push || echo "No changes to commit"
          
